### ISSUE TITLE
Wrong total if params.knex is set

### ISSUE THREAD

**Issue by sylvainlap** [feathersjs-ecosystem/feathers-knex#121]
If params.knex is set, params.query is bypassed, and the knex query is executed insted. However, for the count query (ie total), the params.query is taken into account (instead of params.knex), and results in a wrong total.

I think this is inconsistant, shouldn't params.knex, if set, should be used to compute the count query?

**Comment by daffl** [comment]
That makes sense. Can you try if it works changing https://github.com/feathersjs/feathers-knex/blob/master/src/index.js#L167 to

```js
let countQuery = (params.knex || this.db(params)).count(`${this.id} as total`);
```

**Comment by sylvainlap** [comment]
No, that does not work. `params.knex` can be a complicated request, wheres `this.db(params))` is just `select * from table`. The `count` on `params.knex` is not working.

**Comment by daffl** [comment]
What is `.count` returning for a custom query? If that doesn't work I don't see how we can support `total` at all in that case.

**Comment by sylvainlap** [comment]
Ok, you should precise that pagination (total, limit, skip) is not supported when params.knex is set.
I close the issue.

**Comment by daffl** [comment]
I'd leave it open. We have to check if the query is customized and skip the count. Do you have an example customized query where the count is wrong?

**Comment by sylvainlap** [comment]
Here is an example.

The hook code:
```
return async function (hook) {
  const { $search } = hook.params.query;

  if ($search) {
    // TODO total is wrong
    Object.assign(hook.params, { query: _.omit(hook.params.query, '$search') });

    const query = this.createQuery({ query: hook.params.query });

    query.where(function () {
      this
        .where('firstname', 'like', `%${$search}%`)
        .orWhere('lastname', 'like', `%${$search}%`);
    });

    Object.assign(hook.params, { knex: query });
  }

  return hook;
};
```

The result:
```
{
    "total": 1001,
    "limit": 10,
    "skip": 0,
    "data": []
}
```

**Comment by daffl** [comment]
I haven't tried it yet, but shouldn't `params.knex.count(`${this.id} as total`);` return the correct total in this case?

**Comment by paflopes** [comment]
Not really, as `$search` is not in the query params anymore and you can't really add it later for `count` since you no longer have the info. I suggest we do something like:

```javascript
  _find (params, count, getFilter = filter) {
    const { filters } = getFilter(params.query || {});
    const q = params.knex || this.createQuery(params);
    // define q2 before $limit or $skip
    const q2 = q.clone();

    // Handle $limit
    if (filters.$limit) {
      q.limit(filters.$limit);
    }

    // Handle $skip
    if (filters.$skip) {
      q.offset(filters.$skip);
    }

    let executeQuery = total => {
      return q.then(data => {
        return {
          total: parseInt(total, 10),
          limit: filters.$limit,
          skip: filters.$skip || 0,
          data
        };
      });
    };

    if (filters.$limit === 0) {
      executeQuery = total => {
        return Promise.resolve({
          total: parseInt(total, 10),
          limit: filters.$limit,
          skip: filters.$skip || 0,
          data: []
        });
      };
    }

    if (count) {
      let countQuery = this.db(params).count(`${this.id} as total`);
      // use the exact same query as subquery and count
      countQuery.from(q2.as(`${this.table}`));

      return countQuery.then(count => count[0].total).then(executeQuery);
    }

    return executeQuery().catch(errorHandler);
  }
```

**Comment by roemhildtg** [comment]
Just ran into this also. If I add a simple where clause to the query in a Before hook (as recommended by the readme) the total property returned is still the total number of records, not the number of records that would be returned by the filtered query. 

I'm using this as a simple case:

```javascript
    find: [
      function(context) {
        const query = this.createQuery({query: context.params.query});
        query.where('details', 'LIKE',  '%test%');
        context.params.knex = query;
        return context;
      }
    ],
```

response:
```json
{
    "total": 5,
    "limit": 10,
    "skip": 0,
    "data": [{
        "id": 4,
    }]
}
```

**Comment by InstanceOfMichael** [comment]
Here's what I've found.

I need this to work:

```
class CustomKnexService extends knexService {
  createQuery (params = {}) {
    const { pipe, interest } =  pickBy(params.query, jsonKeys);
    const q = super.createQuery({
      query: omit(params.query, jsonKeys),
    });

    if (pipe !== 'all') {
         // custom stuff here
    }
    return q;
  }
```
But pagination breaks, unless you also overide `_find`:

```
    if (count) {
      console.log('countQuery', omit(params.query, [...jsonKeys, '$sort']))
      let countQuery = params.knex || this.createQuery({
        query: omit(params.query, ['$sort']),
      }).clearSelect().count(`${this.id} as total`);

      this.knexify(countQuery, omit(params.query, ['$sort']));

      return countQuery.then(count => count[0].total).then(executeQuery);
    }
```
`omit(params.query, ['$sort']),` and `clearSelect()` being imporant, `omit` being from lodash.

Why doesn't count use `params.knex || this.createQuery` ? That makes getting a count for a slightly customized query into a nightmare.

**Comment by daffl** [comment]
No reason. A pull request to change that is very welcome.
