### ISSUE TITLE
Warning message output from hook.js

### ISSUE THREAD

**Issue by sonycamera** [feathersjs-ecosystem/feathers-knex#136]
Version 2.9.0

I'm using transaction.start()/end() hooks in my project. I saw a warning message printed on console in debug:
`(node:3889) Warning: .then() only accepts functions but was passed: [object Object]`

It seems that there is a typo in function end()/rollback() in hook.js:
```
      return trx.commit()
        .then(() => debug('finished transaction %s with success', id))
        .then(hook);
```

When I removed `.then(hook)`, the warning message disappeared.

**Comment by daffl** [comment]
That is definitely not right. Can you change it to

```
      return trx.commit()
        .then(() => debug('finished transaction %s with success', id))
        .then(() => hook);
```

And submit a PR?

**Comment by sonycamera** [comment]
OK, PR created #137

**Comment by daffl** [comment]
Closed via https://github.com/feathersjs-ecosystem/feathers-knex/pull/137
