### ISSUE TITLE
How to implement soft deletes?

### ISSUE THREAD

**Issue by ShimShamSam** [feathersjs-ecosystem/feathers-knex#143]
How would one go about making the remove() operation set a deleted_at column instead of doing an actual delete?

**Comment by daffl** [comment]
Have a look at the [softDelete hook](https://feathers-plus.github.io/v1/feathers-hooks-common/#softDelete)

**Comment by Ajamuar** [comment]
I am unable to make soft delete work even though I have placed the hooks exactly as specified in the examples. Can I have a more thorough example?

**Comment by fahim525** [comment]
@daffl 
I am using softDelete2() method for soft delete. It works fine. 
`const { softDelete2 } = require('feathers-hooks-common');
`
It used remove hooks method, Now I want to delete the record permanently. How may I achieved this ?
Thank you.
