### ISSUE TITLE
nested tables on join

### ISSUE THREAD

**Issue by matbalazsi** [feathersjs-ecosystem/feathers-knex#144]
Hi,
 Using feathers-knex (postgresql), I am trying to nest my tables on a join. Here is an example on how to achieve this with node-postgres. 

https://github.com/brianc/node-postgres/issues/733

`SELECT to_json(a.*) AS table1, to_json(b.*) AS table2
FROM some_table a
LEFT JOIN another_table b ON a.id = b.id`;
With this all rows will be structured as such:

{ table1: { ... },
  table2: { ... } }

However, using:
const query = this.createQuery({ query: hook.params.query });
   query.select(to_json(a.*) AS table1)

 is giving me an error because it assumes that the table name is “to_json(a”. Is there a way to generate raw queries with feathers-knex?

**Comment by daffl** [comment]
You can create raw queries using `this.Model` which is the `db` instance you initially passed.

**Comment by matbalazsi** [comment]
thanks! I wanted to create the join query in a hook, but setting 
`hook.params.knex =   hook.app.service('a').Model.raw('SELECT * FROM etc....');`
doesn't work. Would you suggest creating a new custom service for this query, or is it possible through hooks?

**Comment by matbalazsi** [comment]
I'm closing the issue, thanks for the quick response! If possible, does anyone have any suggestion regarding the best practice for these types of joins (as mentioned in my previous comment)?

**Comment by roelvan** [comment]
This is what works for me (before hook):
```
const query = context.service.createQuery({ query: context.params.query });
    query
      .count('plannings.id as planninRuleCount')
      .leftJoin('planningRules as plr', 'plr.planningId', 'plannings.id')
      .groupBy('plannings.id');
```

**Comment by GUOLIX** [comment]
you can try like this:
find: [
      function (hook) {

        const query = this.db().column('t_wip_type.product_type','t_wip_type.product_type_code','t_wip_type.code_rules','t_wip_code.*').select();

        query.leftOuterJoin('t_wip_type', 't_wip_code.wip_type_id', 't_wip_type.id');

        hook.params.knex = query;

        return hook;
      }],

**Comment by GUOLIX** [comment]
you can try like this:
find: [
      function (hook) {

        const query = this.db().column('t_wip_type.product_type','t_wip_type.product_type_code','t_wip_type.code_rules','t_wip_code.*').select();

        query.leftOuterJoin('t_wip_type', 't_wip_code.wip_type_id', 't_wip_type.id');

        hook.params.knex = query;

        return hook;
      }],
