### ISSUE TITLE
Can't find relation if table name != service name?

### ISSUE THREAD

**Issue by kodayashi** [feathersjs-ecosystem/feathers-knex#150]
### Steps to reproduce

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))

- [X] Tell us what broke. The more detailed the better.

I have a service called "user-roles" and a model called "user-roles" that is tied to a table called "user_roles". When I do `app.service('user-roles').find({})` I get "error:  error: relation "user-roles" does not exist".

If the table name isn't identical to the service name will queries not work? Does there need to be an explicit mapping? All of my services that are a single word are working fine.

I created my service and model with the feathers cli, so it should be wired up properly:

user-roles.service.js:

const createService = require('feathers-knex');
const createModel = require('../../models/user-roles.model');
const hooks = require('./user-roles.hooks');

module.exports = function (app) {
  const Model = createModel(app);
  const paginate = app.get('paginate');

  const options = {
    name: 'user-roles',
    Model,
    paginate
  };

  // Initialize our service with any options it requires
  app.use('/user-roles', createService(options));

  // Get our initialized service so that we can register hooks and filters
  const service = app.service('user-roles');

  service.hooks(hooks);
};

user-roles.model.js:

/* eslint-disable no-console */

// user-roles-model.js - A KnexJS
//
// See http://knexjs.org/
// for more of what you can do here.
module.exports = function (app) {
  const db = app.get('knexClient');
  const tableName = 'user_roles';
  db.schema.hasTable(tableName).then(exists => {
    if(!exists) {
      db.schema.createTable(tableName, table => {
        table.increments('id').primary();
        table.string('name').unique().notNull();
        table.boolean('is_internal').notNull();
        table.timestamps(true, true);
      })
        .then(() => console.log(`Created ${tableName} table`))
        .catch(e => console.error(`Error creating ${tableName} table`, e));
    }
  });

  return db;
};

- [X] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc.

### Expected behavior
Tell us what should happen

Given the files above, I would think knex could query the user_roles table properly.

### Actual behavior
Tell us what happens instead

It looks like since the service name is 'user-roles', knex is trying to query a relation called 'user-roles' instead of the one defined in the model ('user_roles').

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

  "dependencies": {
    "@feathersjs/authentication": "^2.1.2",
    "@feathersjs/authentication-jwt": "^2.0.0",
    "@feathersjs/authentication-local": "^1.1.0",
    "@feathersjs/configuration": "^1.0.2",
    "@feathersjs/errors": "^3.3.0",
    "@feathersjs/express": "^1.2.0",
    "@feathersjs/feathers": "^3.1.3",
    "@feathersjs/socketio": "^3.2.0",
    "compression": "^1.7.1",
    "cors": "^2.8.4",
    "feathers-knex": "^3.0.2",
    "helmet": "^3.11.0",
    "knex": "^0.14.3",
    "pg": "^7.4.1",
    "serve-favicon": "^2.4.5",
    "winston": "^2.4.0"
  },
  "devDependencies": {
    "eslint": "^4.18.0",
    "mocha": "^5.0.1",
    "request": "^2.83.0",
    "request-promise": "^4.2.2"
  }

**NodeJS version**:

**Operating System**:

**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by daffl** [comment]
Looks like the generator is setting this up the wrong way, does it?

**Comment by kodayashi** [comment]
@jerfowler - Yep that was it, thanks!
@daffl - I changed the table name in the model file after generating so I'm not sure there was an issue with the generation. Just didn't realize that option above was for the table's name (thought it was the service name).

**Comment by eric-burel** [comment]
Hi I had the same confusion. Could the name field be renamed to "tableName", and the service name explicitely defined as a "const serviceName="foobar; service = app.service(serviceName)"? That sounds like a noob issue but this kind of thing makes a huge difference for a first-timer.
