### ISSUE TITLE
How to properly extend knex service

### ISSUE THREAD

**Issue by lukaszczerpak** [feathersjs-ecosystem/feathers-knex#155]
### Steps to reproduce

When my service class extends knex service, a newly created instance of my service is pure knex service instance.

```js
const Service = require('feathers-knex')

class CaseService extends Service {
  testMethod() {
    console.log('Hello from test method!')
  }
}

module.exports = function init (options) {
  return new CaseService(options)
}

module.exports.CaseService = CaseService
```

Simple call to the test method during service initialization:

```js
const createService = require('./case.class.js')
...
module.exports = function (app) {
...
  // Initialize our service with any options it requires
  let service1 = createService(options)
  service1.testMethod()
...
```

throws an error:

```
  service1.testMethod()
           ^

TypeError: service1.testMethod is not a function
```

### Expected behavior

Original intention was to extend knex service class and override some functions as I need custom stuff in there. 

### Actual behavior

Looks like my class is totally ignored and returned instance is knex service.

### System configuration

**Module versions**: feathers-knex: 3.0.6
**NodeJS version**: 8.11.1
**Operating System**: macOS Sierra (10.12.6)

### Workaround

The following code works though (extending knex service by using builtin function extend()):

```js
const Service = require('feathers-knex')

class CaseService {
  testMethod() {
    console.log('Hello from test method!')
  }
}

module.exports = function init (options) {
  return new Service(options).extend(new CaseService(options))
}

// disabled for safety reasons
// module.exports.CaseService = CaseService
```

**Comment by lukaszczerpak** [comment]
Many thanks! Yeah, it works now :)

**Comment by daffl** [comment]
👍
