### ISSUE TITLE
Unable to order by calculated column

### ISSUE THREAD

**Issue by thngdude** [feathersjs-ecosystem/feathers-knex#158]
### Steps to reproduce

```
function applyAge (options = {}) {
  return async context => {
    const query = context.service.createQuery(context.params);
    const curDateStr = (new Date()).toISOString();
    const raw = context.service.Model.raw;
    query.select(raw('DATEDIFF("' + curDateStr + '", STR_TO_DATE(birthdate, "%d/%m/%Y")) / 365.25 as age'));
    query.orderBy('age', 'desc'); <=== This line
    context.params.knex = query;
    return context;
}
```
This can be achieved in mysql pretty easily, but achieving the same result with feathers-knex seems unachievable. The above code returns users and adds a calculated column with their age. If I make a find service call with a sort on the calculated 'age' column, I get the following error:

`BadRequest: select count(`user`.`id`) as `total` from `user` order by `age` desc - Unknown column 'age' in 'order clause'
`
By the way, without the orderBy line marked "This line", the hook will return the age column as expected. However, I NEED to be able to sort/orderBy the calculated age column, too.

**Comment by InstanceOfMichael** [comment]
Your issue looks similar to https://github.com/feathersjs-ecosystem/feathers-knex/issues/121
