### ISSUE TITLE
$in and $nin with a single non-array parameter throw a BadRequest

### ISSUE THREAD

**Issue by coreysan** [feathersjs-ecosystem/feathers-knex#174]
### Steps to reproduce

1. Pull the latest feathers-knex
1. Add this test: 

    ```js
    describe.only('inclusion/exclusion', () => {
      it('$in works properly', () => {
        app.service('/people').create([{
          name: 'Dada',
          age: 1
        }]);

        // /people?name[$in]=Dave
        return app.service('/people').find({
          query: {
            name: { $in: 'Dada' } // change to ['Dada'] to fix the test
          }
        }).then(data => {
          expect(data.length).to.equal(1);
          expect(data[0].name).to.be.equal('Dada');
          expect(data[0].age).to.be.equal(1);
          app.service('/people').remove(null);
        });
      });
    });
    ```
1. Note the failure

#### What's going on here...

Array query parameters with one element may be parsed as follows: 
```
GET /people?hats[$in]=black
=> context.params.query = { hats: { $in: 'black' } }
```

A query parameter array of multiple values is always parsed as an array: 
```
GET /people?hats[$in]=black&hats[$in]=white
=> context.params.query = { hats: { $in: ['black', 'white'] } }
```

Note that this is the default behaviour with this setup: 
```
// feathersjs src/index.js: 
// ...
// This uses the `qs` library to process the query string
app.use(express.urlencoded({ extended: true }));
```

And in qs, they state that the above is true: 
![image](https://user-images.githubusercontent.com/959458/48099321-123b6980-e1d4-11e8-80e2-97cc969efff0.png)

---

Also note that this may not technically be a problem with feathers-knex. Happy to move this 

### Expected behavior
`$in` or `$nin` with a single value (not array) should be converted to an array before being knexified. 

### Actual behavior
A BadRequest error is thrown: 
```
BadRequest: select `people`.* from `people` where `name` in 'Dada' - SQLITE_ERROR: near "?": syntax error
```

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
Feathers-knex v4.0.0

**NodeJS version**:
v9.11.1

**Operating System**:
MacOS High Sierra

**Browser Version**:
n/a

**React Native Version**:
n/a

**Module Loader**:
n/a

**Comment by daffl** [comment]
At the moment, `$in` and `$nin` are always expected to be an array. This can be either done by manually converting it in a hook or instructing `qs` to parse an array by changing the queries to `[$in][]=black`. We might be able to include automated conversion in the query syntax.
