### ISSUE TITLE
No record found for id '${id}'

### ISSUE THREAD

**Issue by RaduGrama** [feathersjs-ecosystem/feathers-knex#184]
Run code like `service('abc').patch(1, values)` fails with the error above. It looks like in line 263 the test `items.length === 1` returns false because `items` has a `data` field that has a `length`.

In release 4.0.0 there was an `const items = page.data;` statement a few lines above, but it's gone starting with 5.0.0 and both 5.0.0 and 5.0.1 exhibit this issue.

**Comment by daffl** [comment]
Do you have more information about your setup? This simple case is being tested and should be working.

If you have a look at the [migration guide](https://crow.docs.feathersjs.com/migrating.html#querying-by-id) you can see that the `query` will now be included when trying to look up the record. If you do not want that you will have to clean up the query in a hook.

**Comment by jbiffis** [comment]
Running into the same issue.  Fails in the same spot. `items.data` has the returned object from db but `items.length` returns false.  

I'm not sure how to clean up the query in a hook.  There is no query that I'm sending with this call.  In my case: `return context.app.service('api/teams').patch(context.id, { 'is_active' : false})`

**Comment by lvivier** [comment]
I'm having the same issue as well. In my case, it only happens if `{paginate: {default: n}}` is in the options for the service. I'll try to follow up with a small test case.

**Comment by daffl** [comment]
Yep, that was it. Fixed in v5.0.3
