### ISSUE TITLE
Overriding knex-adapter default post-create behaviour

### ISSUE THREAD

**Issue by naorzr** [feathersjs-ecosystem/feathers-knex#207]
Hey there,

After inserting an item using the 'create' service method knex-adapter automatically gets the item inserted from the table.
Is there a way to override this 'get' behaviour? 
I for example have a special object i return to the user, and not the database fields directly.

Ultimately it would be best if it could use the service get method, instead of a query get.

**Comment by daffl** [comment]
You can [extend the adapter](https://docs.feathersjs.com/api/databases/common.html#classes-es6) and return the `get` result.

```js
const { Service } = require( 'feathers-knex');

class MyService extends Service {
  async create(data, params) {
    const created = await super.create(data, params);

    return this.get(created.id, params);
  }
}
```

**Comment by naorzr** [comment]
Thanks but this aint working, and it's impossible to debug, I'm only recieving 
```
{
    "name": "GeneralError",
    "message": "Not Acceptable",
    "code": 500,
    "className": "general-error",
    "data": {},
    "errors": {}
}
```
even though ```this.get(created.id,params);```` returns a valid response.
I've even tried this , but it's still fail with the same ambiguous error
```
const { Service } = require( 'feathers-knex');

class MyService extends Service {
  async create(data, params) {
    return Promise.resolve({test: 'test'})
  }
}
```

**Comment by daffl** [comment]
I can't reproduce this. A Not Acceptable error usually happens when you don't set a `Content-Type` header for a POST request.

**Comment by naorzr** [comment]
```Content-Type``` was set, but it was an additional header ```Accept``` which was set(a leftover from a duplicate in postman) that caused it.
Thanks for all the help, much appreciated!
