### ISSUE TITLE
.returning() is not supported by mysql and will not have any effect.

### ISSUE THREAD

**Issue by mohanagy** [feathersjs-ecosystem/feathers-knex#209]
I'm using MySQL as database and knex 
Mysql doesn't support returning 
so I got this message 
.returning() is not supported by MySQL and will not have any effect.

**Comment by afaonline** [comment]
I see the same warning

 feathers-knex v. 5.1.0, client = "mysql2"

**Comment by daffl** [comment]
Fixed in v6.0.1
