### ISSUE TITLE
Nested transactions stepping on each other

### ISSUE THREAD

**Issue by KidkArolis** [feathersjs-ecosystem/feathers-knex#217]
Not sure this is an issue. But it's something that we ran into at first. It's easy to workaround, but wasn't easy to know what's going on.

The issue is really simple:

1. say you call service a which starts a transaction
2. service a then calls service b passing all the params through
3. service b also starts a transaction
4. service b completes
5. service a now hangs / crashes / etc

That's because Step 3 overwrites the `params.transaction`:
https://github.com/feathersjs-ecosystem/feathers-knex/blob/6bc2d9da0b8628cc10c9c657c085aba52338ea55/lib/hooks.js#L30

Step 4 overwrites the `params.transaction` once again:
https://github.com/feathersjs-ecosystem/feathers-knex/blob/6bc2d9da0b8628cc10c9c657c085aba52338ea55/lib/hooks.js#L56

This means that in step 5, the transaction is never committed, since that end() hook lost the reference to it's transaction.

Now, the best thing imo is to **never share params**, always clone, e.g. `{ ...params }`. This solves the issue.

But wondering if there's more we should do here:

1. Add a note in README in the transaction section about this (happy to PR something).
2. Rewrite the logic to not overwrite when params are shared - not sure that's possible! Service A might make multiple nested service calls, how do you track who started what transaction (only idea here is to **put transaction on `context` instead of `params` which is distinct in each service lifecycle, would that be a better implementation?**).
3. Solve this later if Feathers introduces the koa style closure-stateful middleware.

cc @vonagam

**Comment by vonagam** [comment]
Yes, solution with `{ ...params }` is a right one.

You can't put it on `context` because it will not be available inside a service method (since only `id`, `data` and `params` are available to standard ones).

**Comment by vonagam** [comment]
One solution might be replacing code inside hooks from:

```js
context.params.transaction = x;
``` 

with:

```js
context.params = { ...context.params, transaction: x };
```

I think this is a common issue for hooks which @daffl talks about.

**Comment by daffl** [comment]
I'm definitely going to add a clone hook to the new Cookbook that helps avoid these issues. In this case I'd say it's a bug and it should be changed to what @vonagam is suggesting.
