### ISSUE TITLE
Feathers-knex, REST and PostGIS — include examples?

### ISSUE THREAD

**Issue by irrg** [feathersjs-ecosystem/feathers-knex#240]
### Steps to reproduce

I've just started implementing a simple API that uses a single PostGIS column for some location math. I've gone through all the docs for feathers-knex and feathers.js in general pertaining to the REST interface, but I'm stumped on how to actually POST a new record into my table.

Here's a simplified schema:

```javascript
knex.schema.createTable('locations', table => {
      table.increments('id');
      table.string('name');
      table.specificType('geo', 'geometry(point, 4326)');
})
```
and a simplified JSON body for a `POST` to `/locations`:

```json
{
	"name": "Indiana Convention Center",
	"geo": {
    	"type": "Point",
    	"coordinates": [-86.1644, 39.7645]
	}
}
```

### Expected behavior
Perhaps a naive take, but this felt like a place where a nested JSON object should slip right into the table.

### Actual behavior
```
    "message": "insert into \"locations\"  \"geo\", \"name\") values ($1, $2) returning \"id\" - parse error - invalid geometry",
```
If the way I'm posting the data is incorrect, it'd be good to have an example for this kind of column type (or other, complex column types).

### System configuration

Node v10.16.0
Postgres 11.5
Postgis 2.5

**Comment by roemhildtg** [comment]
Hi - I too am wondering about this. I'm using feathers-knex to serve out and update a table with a geometry (postgis) field `geom`. 

I have the read methods serializing the geom field to GeoJSON type using a before hook:

```javascript
// GeoJSON -> geometry
function toGeoJson(context){
    const query = context.service.createQuery(context.params);
    // update the geom field to convert to geojson. 
    // Not sure if this is right- but it appears to be working
    query.select(context.service.knex.raw('st_asgeojson(geom) geom'));
    context.params.knex = query;
    return context;
}
```

Now I'm working on serializing the JSON that gets passed to feathers for update and create methods. Here is where I'm at so far:

```javascript
(context) => {
        const query = context.service.createQuery(context.params);
        query.insert({
            geom: context.service.knex.raw('ST_GeomFromGeoJSON(?)', [context.data.geom]),
        });
        context.params.knex = query;
        return context;
    }
```

But it doesn't appear to be converting the geometry because knex gives this error: 
```javascript
{
  method: 'insert',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [
    2020-09-30T16:17:18.344Z,
    'Gregg',
    '{"type":"Polygon","coordinates":[[[-93,44],[-93,45],[-94,45],[-94,46],[-93,44]]]}',
    'test location',
    2020-09-30T16:17:18.344Z,
    'Gregg',
    'gregg',
    'Greggs test project',
    'R-123-123',
    'Open'
  ],
  __knexQueryUid: '693adf90-0338-11eb-acd6-a5ecb2c21e09',
  sql: 'insert into "project" ("created_at", "created_by", "geom", "location", "modified_at", "modified_by", "ownername", "project_name", "project_number", "status") values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?) returning "id"',
  returning: [ 'id' ]
}
error: GeneralError: insert into "project" ("created_at", "created_by", "geom", "location", "modified_at", "modified_by", "ownername", "project_name", "project_number", "status") values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) returning "id" - parse error - invalid geometry
    at new GeneralError (/Users/groemhildt/projects/wsb-services/node_modules/@feathersjs/errors/lib/index.js:177:17)
    at errorHandler (/Users/groemhildt/projects/wsb-services/node_modules/feathers-knex/lib/error-handler.js:84:25)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by roemhildtg** [comment]
Update: The get hook also does not work (mentioned above). Looks like if you pass a query in the before hook of the `get` function, the hook turns the query into a `find` result where the result contains more than one record.
