### ISSUE TITLE
Create method with knex plugged with mssql database returns no id. Gets General Error in feathers api  

### ISSUE THREAD

**Issue by Oumar24sh** [feathersjs-ecosystem/feathers-knex#243]
feathers-knex\lib\index  : line 245

 const returning = client === "pg" || client === "oracledb" || **client === "mssql"**? [this.id] : [];

Added mssql as client in ternary and it worked (**in bold**)
please update in future release

**Comment by daffl** [comment]
You can make the change directly by clicking the edit link on https://github.com/feathersjs-ecosystem/feathers-knex/blob/master/lib/index.js and submitting a pull request. Then we can make a future release right away.

**Comment by Oumar24sh** [comment]
Done 👍. Thanks for the quick reply.
