### ISSUE TITLE
Meta fields missing (`total`, `skip`, ...)

### ISSUE THREAD

**Issue by strarsis** [feathersjs-ecosystem/feathers-knex#272]
### Steps to reproduce
- Use `feathers-knex` with FeathersJS (KnexJS - SQLite database).
- Make a FIND/GET request. Notice that only the data itself is returned, meta fields like `total` are missing. This also prevents the pagination to work completely in `react-admin`.

### Expected behavior
Meta fields (`total`, ...) should also be send. `react-admin´ pagination should work completely.

### Actual behavior
Meta fields (`total`, ...) are missing. `react-admin` pagination doesn't work.

### System configuration
Latest FeathersJS, KnexJS, stable `react-admin` (`v3.x`).

**Module versions** (especially the part that's not working):

**NodeJS version**: NodeJS LTS (`v16.14.0`).

**Operating System**: WSL 2 / Ubuntu

**Browser Version**: Latest Chrome on Windows 10

**React Native Version**: (not applicable)

**Module Loader**: Based off example FeathersJS app project.

Related issue: https://github.com/josx/ra-data-feathers/issues/180

**Comment by daffl** [comment]
Did you set the `paginate` [service options](https://docs.feathersjs.com/api/databases/common.html#service-options)?

**Comment by strarsis** [comment]
@daffl: Yes, that was the problem! Setting it added those meta fields!
