### ISSUE TITLE
Search with $ilike a value into a json column type

### ISSUE THREAD

**Issue by Zorkham** [feathersjs-ecosystem/feathers-knex#286]
Hello team !

I have a "users" table in my PostgreSQL DB. In this table I have an "address" column which is a "json" type column (table.json)

Here is an example of the address value : { "city": "London", "longitude": "XXX", "latitude": "XXX" }

I'm trying to do a request (in my Feathers.js client) to find all records that match the value searched on my front end.

Does it possible to do that ?

Thanks,

Cédric

**Comment by kvagajack** [comment]
@Zorkham Did you figure out how to query JSON column data?
